apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: django-app-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.django.pv.app.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-app-storage
  hostPath:
    path: {{ .Values.django.pv.app.path }}
  nodeAffinity:
    required: {{ toYaml .Values.whgAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.django.pv.app.storage }}
  volumeName: django-app-pv  # Reference the PV
  storageClassName: django-app-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: django-static-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.django.pv.static.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-static-storage
  hostPath:
    path: {{ .Values.django.pv.static.path }}
  nodeAffinity:
    required: {{ toYaml .Values.whgAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.django.pv.static.storage }}
  volumeName: django-static-pv  # Reference the PV
  storageClassName: django-static-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: django-media-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-media-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.django.pv.media.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-media-storage
  hostPath:
    path: {{ .Values.django.pv.media.path }}
  nodeAffinity:
    required: {{ toYaml .Values.whgAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.django.pv.media.storage }}
  volumeName: django-media-pv  # Reference the PV
  storageClassName: django-media-storage
