apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: django-pgbackrest
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgbackrest-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.pv.pgbackrest.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-pgbackrest
  local:
    path: {{ .Values.postgres.pv.pgbackrest.path }}
  nodeAffinity:
    required: {{ toYaml .Values.whgAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgbackrest-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pv.pgbackrest.storage }}
  volumeName: pgbackrest-pv # Reference the PV
  storageClassName: django-pgbackrest