apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: django-postgres
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.pv.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-postgres
  local:
    path: {{ .Values.postgres.pv.postgres.path }}
  nodeAffinity: {{- toYaml .Values.whgNodeAffinity | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pv.postgres.storage }}
  volumeName: postgres-pv # Reference the PV
  storageClassName: django-postgres