apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.redis.pv.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: {{ .Values.redis.pv.path }}
  nodeAffinity:
    required: {{ toYaml .Values.whgAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.pv.storage }}
  volumeName: redis-pv  # Reference the PV
  storageClassName: redis-storage