apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpack
  namespace: {{ .Values.namespace }}
  labels:
    app: webpack
spec:
  replicas: {{ .Values.webpack.replicaCount }}
  selector:
    matchLabels:
      app: webpack
  template:
    metadata:
      labels:
        app: webpack
    spec:
      affinity:
        nodeAffinity: {{ toYaml .Values.whgDevAffinity | nindent 10 }}
      initContainers:
        - name: webpack-build
          image: node:18-alpine
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Starting Webpack installation in initContainer..."
              cp -v -L /config-temp/* /config/ # Copy files from the config-volume into the PersistentVolume
              cd /config
              npm install
              echo "Webpack installation completed."
          volumeMounts:
          - name: config-volume
            mountPath: /config-temp
          - name: django-app-volume
            mountPath: /app
          - name: webpack-build-volume
            mountPath: /config # This is where the build artifacts will be stored
      containers:
        - name: webpack
          image: node:18-alpine
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Starting Webpack watch in main container..."
              cd /config
              npx webpack --watch --config /config/webpack.config.js
          ports:
          - containerPort: {{ .Values.webpack.port }}
          workingDir: /app
          volumeMounts:
          - name: django-app-volume
            mountPath: /app
          - name: webpack-build-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: webpack-config
          items:
            - key: package.json
              path: package.json
            - key: webpack.config.js
              path: webpack.config.js
      - name: webpack-build-volume
        persistentVolumeClaim:
          claimName: webpack-build-pvc
      - name: django-app-volume
        persistentVolumeClaim:
          claimName: django-app-pvc
