apiVersion: v1
kind: ConfigMap
metadata:
  name: webpack-config
  namespace: {{ .Values.namespace }}
data:
  package.json: |
    {{ .Files.Get "package.json" | indent 4 }}
  webpack.config.js: |
    {{ .Files.Get "webpack.config.js" | indent 4 }}
