apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: webpack-build-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webpack-build-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.webpack.pv.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "webpack-build-storage"
  hostPath:
    path: {{ .Values.webpack.pv.path }}
  nodeAffinity: {{- toYaml .Values.whgDevAffinity | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpack-build-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.webpack.pv.storage }}
  storageClassName: "webpack-build-storage"
