# Default values for plausible-ce chart
namespace: whg
createNamespace: false

imagePullPolicy: IfNotPresent

# Expose plausible as NodePort
plausible:
  image: ghcr.io/plausible/community-edition:v3.0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    type: NodePort
    port: 8000        # NodePort service port
    targetPort: 8000  # container port (plausible's HTTP_PORT)
    nodePort: 30100

postgres:
  image: postgres:16-alpine
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

clickhouse:
  image: clickhouse/clickhouse-server:24.12-alpine
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 2
  service:
    type: ClusterIP
    port: 8123    # HTTP interface used by Plausible's CLICKHOUSE_DATABASE_URL
    targetPort: 8123

# Optionally set nodeSelector, tolerations, resources here
pod:
  nodeSelector:
    role: backend
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              # Prefer to avoid tileserver node if possible
              - key: tileserver
                operator: NotIn
                values:
                  - "true"
  tolerations: []
  resources: {}

# Security / secrets
secret:
  existingSecretName: whg-secret

# Healthcheck / readiness settings (kept simple)
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
