replicaCounts:
  configserver: 3  # Ensure quorum for ZooKeeper
#  container: 2     # Adjust based on expected traffic
#  content: 3       # For high availability and redundancy

image:
  repository: vespaengine/vespa
  pullPolicy: IfNotPresent
  tag: "8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  container:
    runAsUser: 1000
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: contour
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: index.whgazetteer.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: vespa-tls

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# MetalLB LoadBalancer configuration (useful if you are exposing services via LoadBalancer)
loadBalancerIP: "auto"  # or specify an IP if you are using MetalLB

flannel:
  enabled: true  # Enable Flannel for networking in your cluster
  cniVersion: "v0.26.1"

certManager:
  enabled: true
  issuerRef:
    name: "letsencrypt-prod"
    kind: ClusterIssuer

configserverConfig:
  servers: >
    vespa-configserver-0.vespa-internal.default.svc.cluster.local,
    vespa-configserver-1.vespa-internal.default.svc.cluster.local,
    vespa-configserver-2.vespa-internal.default.svc.cluster.local
  configserverJvmArgs: "-Xms32M -Xmx128M" # TODO: Comment out for production
  configproxyJvmArgs: "-Xms32M -Xmx32M" # TODO: Comment out for production

nodeAffinities:
  admin:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: vespa-role-admin
              operator: In
              values:
                - "true"

pv:
  - name: var
    storageSize: 5Gi
    mountPath: /opt/vespa/var
  - name: logs
    storageSize: 5Gi
    mountPath: /opt/vespa/logs
  - name: workspace
    storageSize: 1Gi
    mountPath: /workspace