namespace: vespa

replicaCounts:
  # Ensure quorum for ZooKeeper: if you increase this value, you must create additional directories for PVs
  configserver: 3
  admin: 1         # Only one admin node is needed
  content: 1       # TODO: Increase this value for production
  feed: 2
  query: 2

image:
  repository: vespaengine/vespa
  pullPolicy: IfNotPresent
  tag: "8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  container:
    runAsUser: 1000
#    fsGroup: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: contour
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: index.whgazetteer.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: vespa-tls

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# MetalLB LoadBalancer configuration (useful if you are exposing services via LoadBalancer)
loadBalancerIP: "auto"  # or specify an IP if you are using MetalLB

flannel:
  enabled: true  # Enable Flannel for networking in your cluster
  cniVersion: "v0.26.1"

certManager:
  enabled: true
  issuerRef:
    name: "letsencrypt-prod"
    kind: ClusterIssuer

resources:
  configserver:
    requests:
      memory: "4G"
    limits:
      memory: "4G"
  admin:
    requests:
      memory: "1G"
    limits:
      memory: "1G"
  content:
    requests:
      memory: "1G"
    limits:
      memory: "1G"
  feed:
    requests:
      memory: "1.5G"
    limits:
      memory: "1.5G"
  query:
    requests:
      memory: "1.5G"
    limits:
      memory: "1.5G"

configserver:
  configserverJvmArgs: "-Xms32M -Xmx128M" # TODO: Comment out for production
  configproxyJvmArgs: "-Xms32M -Xmx32M" # TODO: Comment out for production
  pvRootPath: "/data/k8s/vespa-config"
  pvs:
    - name: var
      storageSize: 5Gi
      mountPath: /opt/vespa/var
    - name: logs
      storageSize: 5Gi
      mountPath: /opt/vespa/logs
    - name: workspace
      storageSize: 1Gi
      mountPath: /workspace

content:
  pv:
    name: var
    storageSize: 5Gi
    rootPath: "/data/k8s/vespa-content-var"
    mountPath: /opt/vespa/var

nodeAffinities:
  admin:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: vespa-role-admin
              operator: In
              values:
                - "true"
  content:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: vespa-role-content
              operator: In
              values:
                - "true"