apiVersion: v1
kind: PersistentVolume
metadata:
  name: vespa-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vespa-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
            - all
            - general
  hostPath:
    path: "/data/k8s/vespa"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vespa-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vespa-storage