apiVersion: v1
kind: ConfigMap
metadata:
  name: whg-config
data:

  # Hostname
  hostname: "place.whgazetteer.org" # Temporary subdomain, pending switch to 'whgazetteer.org'

  # Django
  image-version: "0.1.4"

  # Database
  db-user: "whgadmin"
  db-name: "whgv3beta"

  # Postgres HBA - IP range defined by flannel (see flannel-config.yaml)
  pg-hba: |
    local   all             all                                  trust
    host    all             all             10.244.0.0/16        trust
    host    replication     all             10.244.0.0/16        trust
    host    all             all             0.0.0.0/0            reject