apiVersion: v1
kind: ConfigMap
metadata:
  name: whg-config
data:

  # Hostname
  hostname: "place.whgazetteer.org" # Temporary subdomain, pending switch to 'whgazetteer.org'

  # Django
  image-version: "0.1.4"

  # Database
  db-user: "whgadmin"
  db-name: "whgv3beta"
