apiVersion: v1
kind: Service
metadata:
  name: phonetics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
