apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pv.name }}
spec:
  capacity:
    storage: {{ .Values.nfs.pv.capacity }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.nfs.pv.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.nfs.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.nfs.pv.hostPath }}
---
{{- range .Values.nfs.pvc.nameSpaces }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ishi-pvc
  namespace: {{ . }}
spec:
  accessModes:
{{ toYaml $.Values.nfs.pv.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ $.Values.nfs.pv.capacity }}
  volumeName: {{ $.Values.nfs.pv.name }}
  storageClassName: ""
---
{{- end }}