apiVersion: v1
kind: PersistentVolume
metadata:
  name: ix1-whcdh-pv
spec:
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /minikube-whcdh
{{/*  nfs:*/}}
{{/*    path: /mnt/tank/crc/whcdh*/}}
{{/*    server: ix1.crc.pitt.edu*/}}
{{/*    readOnly: false*/}}
{{/*  mountOptions:*/}}
{{/*    - nfsvers=4.2*/}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ix1-whcdh-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: ix1-whcdh-pv
  storageClassName: ""  # <-- REQUIRED for static binding
