apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pv.name }}
spec:
  capacity:
    storage: {{ .Values.nfs.pv.capacity }}
  volumeMode: Filesystem
  accessModes: {{ .Values.nfs.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.nfs.pv.reclaimPolicy }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
    readOnly: {{ .Values.nfs.readOnly }}
  mountOptions: {{ .Values.nfs.mountOptions }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfs.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.nfs.pv.accessModes }}
  resources:
    requests:
      storage: {{ .Values.nfs.pv.capacity }}
  volumeName: {{ .Values.nfs.pv.name }}
  storageClassName: {{ .Values.nfs.pvc.storageClassName }}
