apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  namespace: management
type: Opaque
stringData:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ .Values.caCert }}
        server: "https://{{ .Values.minikubeIp }}:8443"
      name: minikube
    contexts:
    - context:
        cluster: minikube
        user: minikube
      name: minikube
    current-context: minikube
    kind: Config
    preferences: {}
    users:
    - name: minikube
      user:
        client-certificate-data: {{ .Values.clientCert }}
        client-key-data: {{ .Values.clientKey }}