apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
  namespace: management
  labels:
    app: gazetteer-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gazetteer-management
  template:
    metadata:
      labels:
        app: gazetteer-management
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup | default 53644 }}
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          command: ["git", "clone", "https://github.com/WorldHistoricalGazetteer/place", "/apps/repository"]
          volumeMounts:
            - name: empty-dir-volume
              mountPath: /apps/repository
      containers:
        - name: helm
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              ls -la /ix1/whcdh
              export KUBECONFIG=/root/.kube/config &&
              cd /apps/repository &&
              chmod +x *.sh &&
              ls -la &&
              python ./deployment/app/api.py
          ports:
            - containerPort: 8000
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser | default 1001 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1001 }}
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /root/.kube
            - name: empty-dir-volume
              mountPath: /apps/repository
            - name: ix1-whcdh-volume
              mountPath: /ix1/whcdh
          envFrom:
            - secretRef:
                name: github-token
          env:
            - name: NOTIFY_PITT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: whg-secret
                  key: notify-pitt-token
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig
        - name: empty-dir-volume
          emptyDir:
            sizeLimit: 1Gi
        - name: ix1-whcdh-volume
          persistentVolumeClaim:
            claimName: ix1-whcdh-pvc
