apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
  namespace: management
  labels:
    app: gazetteer-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gazetteer-management
  template:
    metadata:
      labels:
        app: gazetteer-management
    spec:
      initContainers:
      - name: setup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            git clone https://github.com/WorldHistoricalGazetteer/place /apps/repository &&
            export KUBECONFIG=/root/.kube/config &&
            cd /apps/repository &&
            chmod +x *.sh &&
            ./remove-secrets.sh &&
            if [ $? -ne 0 ]; then
              echo "remove-secrets.sh failed"
              exit 1
            fi &&
            ./load-secrets.sh &&
            if [ $? -ne 0 ]; then
              echo "load-secrets.sh failed"
              exit 1
            fi
        volumeMounts:
          - name: kubeconfig-volume
            mountPath: /root/.kube
          - name: empty-dir-volume
            mountPath: /apps/repository
        envFrom:
          - secretRef:
              name: hcp-credentials
      containers:
      - name: helm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            export KUBECONFIG=/root/.kube/config &&
            cd /apps/repository/deployment/app &&
            sleep infinity
        volumeMounts:
          - name: kubeconfig-volume
            mountPath: /root/.kube
          - name: empty-dir-volume
            mountPath: /apps/repository
        envFrom:
          - secretRef:
              name: hcp-credentials
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig
      - name: empty-dir-volume
        emptyDir:
          sizeLimit: {{ .Values.sizeLimit }}