apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
spec:
  capacity:
    storage: {{ .Values.pvStorageSize }}
  accessModes:
    - {{ .Values.accessMode }}
  hostPath:
    path: {{ .Values.pvHostPath }}
  persistentVolumeReclaimPolicy: {{ .Values.reclaimPolicy }}