apiVersion: v1
kind: PersistentVolume
metadata:
  name: plausible-postgres-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plausible-postgres-storage
  hostPath:
    path: /data/k8s/plausible
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - all
          - general
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: plausible-postgres-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: plausible-postgres-storage
provisioner: kubernetes.io/no-provisioner  # using hostPath
reclaimPolicy: Retain  # Ensures data is kept when PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Prevents PV binding until PVC is created