image:
  repository: plausible/analytics
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  storage: 5Gi

redis:
  image: redis:7

secrets:
  name: whg-secret

service:
  type: ClusterIP
  port: 8000
