apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tileserver-exec-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tileserver-exec-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: tileserver-exec-role
  apiGroup: rbac.authorization.k8s.io
