apiVersion: v1
kind: Service
metadata:
  name: tileapi
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    tileapi: "true"
  ports:
    - protocol: TCP
      port: {{ .Values.service.tileapi.port }}
      targetPort: {{ .Values.service.tileapi.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.tileapi.servicePort }}
      {{- end }}
