apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver-gl
  namespace: {{ .Values.namespace }}
  labels:
    tileserver-gl: "true"
    app: tileserver-gl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tileserver-gl: "true"
  template:
    metadata:
      labels:
        tileserver-gl: "true"
        app: tileserver-gl
        tileapi: "true"
    spec:
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      securityContext:
        fsGroup: {{ .Values.securityContext.runAsGroup }}
      initContainers:
        - name: git-sparse-clone
          image: alpine/git
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            git init /mnt/tileserver && \
            git config --global --add safe.directory /mnt/tileserver && \
            cd /mnt/tileserver && \
            git remote get-url origin || git remote add origin {{ .Values.tileserver.git.url }} && \
            git config core.sparseCheckout true && \
            echo "{{ .Values.tileserver.git.sourceFolder }}/" >> .git/info/sparse-checkout && \
            git fetch origin main && \
            git reset --hard origin/main && \
            chmod -R 775 /mnt/tileserver
          volumeMounts:
            - name: tileserver
              mountPath: /mnt/tileserver
            - name: tiles
              mountPath: /mnt/data/tiles
              subPath: tiles
      containers:
      - name: tileserver-gl
        image: {{ .Values.tileserver.image }}:{{ .Values.tileserver.imageTag }}
        imagePullPolicy: {{ .Values.tileserver.imagePullPolicy }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        command: ["bash", "-c"]
        args:
        - |
          ls -la /mnt/tileserver /mnt/data/tiles
          node /mnt/tileserver/reconfiguration/merge-config.js /mnt/tileserver/reconfiguration/base-config.json /mnt/tileserver/configs/config.json /mnt/data/tiles
          node /usr/src/app/src/main.js --config /mnt/tileserver/configs/config.json --verbose
        workingDir: /usr/src/app
        ports:
        - containerPort: {{ .Values.service.tileserver.port }}
        volumeMounts:
        - name: tiles
          mountPath: /mnt/data/tiles
          subPath: tiles
        - name: tileserver
          mountPath: /mnt/tileserver
        resources: {{ toYaml .Values.tileserver.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.tileserver.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.tileserver.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: tile-api
        image: {{ .Values.tileapi.image }}:{{ .Values.tileapi.imageTag }}
        imagePullPolicy: {{ .Values.tileapi.imagePullPolicy }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.tileapi.port }}
        env:
        - name: PORT
          value: "{{ .Values.service.tileapi.port }}"
        - name: TIPPECANOE_IMAGE
          value: "{{ .Values.tippecanoe.image }}"
        - name: TIPPECANOE_IMAGE_TAG
          value: "{{ .Values.tippecanoe.imageTag }}"
        - name: TIPPECANOE_IMAGE_PULL_POLICY
          value: "{{ .Values.tippecanoe.imagePullPolicy }}"
        - name: TIPPECANOE_NAMESPACE
          value: "{{ .Values.namespace }}"
        - name: VESPA_NAMESPACE
          value: "{{ .Values.vespa.namespace }}"
        - name: VESPA_QUERY_HOST
          value: "http://vespa-query.{{ .Values.vespa.namespace }}.svc.cluster.local:8080"
        - name: VESPA_FEED_HOST
          value: "http://vespa-feed.{{ .Values.vespa.namespace }}.svc.cluster.local:8080"
        - name: VESPA_API_HOST
          value: "http://vespa-api.{{ .Values.vespa.namespace }}.svc.cluster.local:8082"
        resources: {{ toYaml .Values.tileapi.resources | nindent 10 }}
        volumeMounts:
        - name: tiles
          mountPath: /mnt/data/tiles
          subPath: tiles
        - name: tileserver
          mountPath: /mnt/tileserver
      volumes:
      - name: tiles
        persistentVolumeClaim:
          claimName: ishi-pvc
      - name: tileserver
        emptyDir: {}
