apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver-gl
  namespace: {{ .Values.namespace }}
  labels:
    tileserver-gl: "true"
    app: tileserver-gl # Required by tile-api service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tileserver-gl: "true"
  template:
    metadata:
      labels:
        tileserver-gl: "true"
        app: tileserver-gl # Required by tile-api service
        tileapi: "true"
    spec:
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      securityContext:
        fsGroup: {{ .Values.securityContext.runAsGroup }}
      initContainers:
        - name: git-sparse-clone
          image: alpine/git
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            git init /mnt/shared/{{ .Values.tileserver.git.targetFolder }} && \
            git config --global --add safe.directory /mnt/shared/src && \
            cd /mnt/shared/{{ .Values.tileserver.git.targetFolder }} && \
            git remote get-url origin || git remote add origin {{ .Values.tileserver.git.url }} && \
            git config core.sparseCheckout true && \
            echo "{{ .Values.tileserver.git.sourceFolder }}/" >> .git/info/sparse-checkout && \
            git fetch origin main && \
            git reset --hard origin/main && \
            # Change ownership of mounted directories to the `node` user and group
            chown -R 999:999 /mnt/shared
            chown -R 999:999 /mnt/data/tiles
            chmod -R 775 /mnt/shared
          volumeMounts:
            - name: tileserver
              mountPath: /mnt/shared
            - name: tiles
              mountPath: /mnt/data/tiles
      containers:
      - name: tileserver-gl
        image: {{ .Values.tileserver.image }}:{{ .Values.tileserver.imageTag }}
        imagePullPolicy: {{ .Values.tileserver.imagePullPolicy }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        command: ["bash", "-c"]
        args:
        - |
          # List mounted directories (for debugging)
          ls -la \
            {{ .Values.pv.tileserver.assets.mountPath }} \
            {{ .Values.pv.tileserver.api.mountPath }} \
            {{ .Values.pv.tileserver.configs.mountPath }} \
            {{ .Values.pv.tileserver.reconfiguration.mountPath }} \
            {{ .Values.pv.tiles.mountPath }}
          # Merge base-config.json and config.json
          node {{ .Values.pv.tileserver.reconfiguration.mountPath }}/merge-config.js {{ .Values.pv.tileserver.reconfiguration.mountPath }}/base-config.json {{ .Values.pv.tileserver.configs.mountPath }}/config.json {{ .Values.pv.tiles.mountPath }}
          # Run Tileserver-GL
          node /usr/src/app/src/main.js --config {{ .Values.pv.tileserver.configs.mountPath }}/config.json --verbose
        workingDir: /usr/src/app
        ports:
        - containerPort: {{ .Values.service.tileserver.port }}
        volumeMounts:
        - name: tiles
          mountPath: {{ .Values.pv.tiles.mountPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.api.mountPath }}
          subPath: {{ .Values.pv.tileserver.api.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.configs.mountPath }}
          subPath: {{ .Values.pv.tileserver.configs.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.reconfiguration.mountPath }}
          subPath: {{ .Values.pv.tileserver.reconfiguration.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.assets.mountPath }}
          subPath: {{ .Values.pv.tileserver.assets.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.mapdata.mountPath }}
          subPath: {{ .Values.pv.tileserver.mapdata.subPath }}
        resources: {{ toYaml .Values.tileserver.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.tileserver.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.tileserver.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: tile-api
        image: {{ .Values.tileapi.image }}:{{ .Values.tileapi.imageTag }}
        imagePullPolicy: {{ .Values.tileapi.imagePullPolicy }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.tileapi.port }}
        env:
        - name: PORT
          value: "{{ .Values.service.tileapi.port }}"
        - name: TIPPECANOE_IMAGE
          value: "{{ .Values.tippecanoe.image }}"
        - name: TIPPECANOE_IMAGE_TAG
          value: "{{ .Values.tippecanoe.imageTag }}"
        - name: TIPPECANOE_IMAGE_PULL_POLICY
          value: "{{ .Values.tippecanoe.imagePullPolicy }}"
        - name: TIPPECANOE_NAMESPACE
          value: "{{ .Values.namespace }}"
        - name: VESPA_NAMESPACE
          value: "{{ .Values.vespa.namespace }}"
        - name: VESPA_QUERY_HOST
          value: "http://vespa-query.{{ .Values.vespa.namespace }}.svc.cluster.local:8080"
        - name: VESPA_FEED_HOST
          value: "http://vespa-feed.{{ .Values.vespa.namespace }}.svc.cluster.local:8080"
        - name: VESPA_API_HOST
          value: "http://vespa-api.{{ .Values.vespa.namespace }}.svc.cluster.local:8082"
        resources: {{ toYaml .Values.tileapi.resources | nindent 10 }}
        volumeMounts:
        - name: tiles
          mountPath: {{ .Values.pv.tiles.mountPath }}
        - name: tileserver
          mountPath: /code/api
          subPath: {{ .Values.pv.tileserver.api.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.configs.mountPath }}
          subPath: {{ .Values.pv.tileserver.configs.subPath }}
        - name: tileserver
          mountPath: {{ .Values.pv.tileserver.mapdata.mountPath }}
          subPath: {{ .Values.pv.tileserver.mapdata.subPath }}
      volumes:
      - name: tiles
        persistentVolumeClaim:
          claimName: tiles-pvc
      - name: tileserver
        persistentVolumeClaim:
          claimName: tileserver-pvc