apiVersion: v1
kind: Service
metadata:
  name: tileapi
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: tileapi
  ports:
    - protocol: TCP
      port: {{ .Values.tileapi.port }}
      targetPort: {{ .Values.tileapi.port }}
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.tileapi.servicePort }}
      {{- end }}
