apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tiles-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tiles-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tiles-storage
  hostPath:
    path: {{ .Values.pv.path }}
  nodeAffinity: {{ toYaml .Values.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiles-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.storage }}
  storageClassName: tiles-storage