apiVersion: v1
kind: Service
metadata:
  name: tileserver-gl
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    tileserver-gl: "true"
  ports:
    - protocol: TCP
      port: {{ .Values.service.tileserver.port }}
      targetPort: {{ .Values.service.tileserver.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.tileserver.servicePort }}
      {{- end }}
