apiVersion: v1
kind: Service
metadata:
  name: vespa-feed
  namespace: {{ .Values.namespace }}
  labels:
    app: vespa
spec:
  # Set LoadBalancer for an endpoint reachable from the internet
  #type: LoadBalancer
  selector:
    app: vespa-feed-container
  ports:
  - name: api
    port: 8080
    targetPort: 8080