image:
  repository: worldhistoricalgazetteer/deployment
  pullPolicy: IfNotPresent
  tag: "0.0.2"

app:
  name: gazetteer-management

containerPort: 8000

service:
  port: 8000
  nodePort: 30000

sizeLimit: 1Gi

hcpClientId: ""
hcpClientSecret: ""
minikubeIp: ""
caCert: ""
clientCert: ""
clientKey: ""