image:
  repository: worldhistoricalgazetteer/deployment
  pullPolicy: IfNotPresent
  tag: "0.0.3"

app:
  name: gazetteer-management

containerPort: 8000

service:
  port: 8000
  nodePort: 30080

securityContext:
  runAsUser: 1001 # 53644
  runAsGroup: 1001
  fsGroup: 16604
  fsGroupChangePolicy: "Always"

sizeLimit: 1Gi

hcpClientId: ""
hcpClientSecret: ""
minikubeIp: ""
caCert: ""
clientCert: ""
clientKey: ""