image:
  repository: worldhistoricalgazetteer/deployment
  pullPolicy: IfNotPresent
  tag: "0.0.2"

sizeLimit: 1Gi

hcpClientId: ""
hcpClientSecret: ""
minikubeIp: ""
caCert: ""
clientCert: ""
clientKey: ""