# -----------------------------------------------------------------------------
# Container image settings
# -----------------------------------------------------------------------------
image:
  repository: worldhistoricalgazetteer/deployment  # Docker image repo
  pullPolicy: IfNotPresent                           # When to pull the image
  tag: "0.0.3"                                      # Image version/tag

# -----------------------------------------------------------------------------
# Application-specific settings
# -----------------------------------------------------------------------------
app:
  name: gazetteer-management  # Name of the deployment/application

containerPort: 8000           # Port the container listens on

# -----------------------------------------------------------------------------
# Kubernetes service settings
# -----------------------------------------------------------------------------
service:
  port: 8000                  # Target port inside the cluster
  nodePort: 30080             # NodePort to expose externally (if using NodePort service type)

# -----------------------------------------------------------------------------
# Pod security context
# -----------------------------------------------------------------------------
securityContext:
  runAsUser: 1001             # UID the container runs as inside the pod
  runAsGroup: 1001            # GID the container runs as inside the pod
  fsGroup: 16604              # Filesystem group for NFS mount (whcdh group on ix1)
  fsGroupChangePolicy: "Always" # Ensure fsGroup ownership is applied to mounted volumes

# -----------------------------------------------------------------------------
# Storage limits (for ephemeral volumes or PVC requests)
# -----------------------------------------------------------------------------
sizeLimit: 1Gi                 # Example resource limit for ephemeral storage

# -----------------------------------------------------------------------------
# NFS / PersistentVolume configuration
# -----------------------------------------------------------------------------
nfs:
  server: ix1.crc.pitt.edu     # NFS server hostname

  # PersistentVolume settings
  pv:
    name: ix1-whcdh-pv          # Name of the PV in Kubernetes
    capacity: 5Ti               # Requested storage size
    accessModes: # PV access mode(s)
      - ReadWriteMany           # Allow multiple pods to read/write
    reclaimPolicy: Retain       # PV is not deleted when PVC is removed
    hostPath: /minikube-whcdh   # hostPath required for minikube NFS workaround (rather than actual NFS config)

  # PersistentVolumeClaim settings
  pvc:
    name: ix1-whcdh-pvc         # Name of the PVC in Kubernetes
    storageClassName: ""        # Empty string required for static PV binding

# -----------------------------------------------------------------------------
# Optional / external credentials (for things like minikube, HCP, TLS)
# -----------------------------------------------------------------------------
hcpClientId: ""
hcpClientSecret: ""
minikubeIp: ""
caCert: ""
clientCert: ""
clientKey: ""
