affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: monitoring
              operator: In
              values:
                - "true"

prometheusPrometheus:
  image: quay.io/prometheus/prometheus
  imageTag: v3.0.1
  imagePullPolicy: IfNotPresent
  pv:
    storageClassName: prometheus-storage
    storage: 10Gi
    path: /data/k8s/prometheus
  spec:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 200Mi
      limits:
        cpu: 2
        memory: 400Mi