apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: no.reply.whgazetteer@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        digitalOcean:
          tokenSecretRef:
            name: whg-secret
            key: kubernetes-cluster-issuer