apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-clickhouse-config
  namespace: {{ .Values.namespace }}
  labels:
    app: plausible-clickhouse
data:
  ipv4-only.xml: |
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
    </clickhouse>
  logs.xml: |
    <clickhouse>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>

        <query_log replace="1">
            <database>system</database>
            <table>query_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
            <engine>
                ENGINE = MergeTree
                PARTITION BY event_date
                ORDER BY (event_time)
                TTL event_date + interval 30 day
                SETTINGS ttl_only_drop_parts=1
            </engine>
        </query_log>

        <!-- Stops unnecessary logging -->
        <metric_log remove="remove" />
        <asynchronous_metric_log remove="remove" />
        <query_thread_log remove="remove" />
        <text_log remove="remove" />
        <trace_log remove="remove" />
        <session_log remove="remove" />
        <part_log remove="remove" />
    </clickhouse>
  low-resources.xml: |
    <!-- https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram -->
    <clickhouse>
        <mark_cache_size>524288000</mark_cache_size>
        <max_thread_pool_size>2</max_thread_pool_size>
        <profile>
            <default>
                <max_threads>1</max_threads>
                <max_block_size>8192</max_block_size>
                <max_download_threads>1</max_download_threads>
                <input_format_parallel_parsing>0</input_format_parallel_parsing>
                <output_format_parallel_formatting>0</output_format_parallel_formatting>
                <background_pool_size>1</background_pool_size>
            </default>
        </profile>
    </clickhouse>
