---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: plausible-postgres
  template:
    metadata:
      labels:
        app: plausible-postgres
    spec:
      {{- if .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.pod.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.affinity }}
      affinity:
        {{- toYaml .Values.pod.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.tolerations }}
      tolerations:
        {{- toYaml .Values.pod.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
        env:
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgres.password }}"
        ports:
          - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.PersistentVolumeClaim.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-clickhouse
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.clickhouse.replicas }}
  selector:
    matchLabels:
      app: plausible-clickhouse
  template:
    metadata:
      labels:
        app: plausible-clickhouse
    spec:
      {{- if .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.pod.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.affinity }}
      affinity:
        {{- toYaml .Values.pod.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.tolerations }}
      tolerations:
        {{- toYaml .Values.pod.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: clickhouse
        image: {{ .Values.clickhouse.image }}
        imagePullPolicy: {{ .Values.clickhouse.imagePullPolicy }}
        resources:
          {{- toYaml .Values.clickhouse.resources | nindent 10 }}
        env:
          - name: CLICKHOUSE_SKIP_USER_SETUP
            value: "1"
        ports:
          - containerPort: 8123
        volumeMounts:
          - name: clickhouse-data
            mountPath: /var/lib/clickhouse
          - name: clickhouse-logs
            mountPath: /var/log/clickhouse-server
          - name: clickhouse-config
            mountPath: /etc/clickhouse-server/config.d
            readOnly: true
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: {{ .Values.clickhouse.PersistentVolumeClaim.name }}
        - name: clickhouse-logs
          emptyDir: {}  # ephemeral logs (K8s handles retention)
        - name: clickhouse-config
          configMap:
            name: plausible-clickhouse-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.plausible.replicas }}
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      {{- if .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.pod.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.affinity }}
      affinity:
        {{- toYaml .Values.pod.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.tolerations }}
      tolerations:
        {{- toYaml .Values.pod.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: plausible
        image: {{ .Values.plausible.image }}
        imagePullPolicy: {{ .Values.plausible.imagePullPolicy }}
        command:
          - sh
          - -c
          - "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
        env:
          - name: BASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-base-url
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-secret-key-base
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-database-url
          - name: CLICKHOUSE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-clickhouse-database-url
          - name: ADMIN_USER_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-admin-user-email
          - name: ADMIN_USER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-admin-user-name
          - name: ADMIN_USER_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-admin-user-pwd
          - name: MAILER_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-mailer-email
          - name: MAILER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-mailer-name
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-smtp-host-addr
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-smtp-host-port
          - name: SMTP_USER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-smtp-user-name
          - name: SMTP_USER_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-smtp-user-pwd
          - name: DISABLE_REGISTRATION
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.existingSecretName }}
                key: plausible-disable-registration
          - name: CRON_ENABLED
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: plausible-cron-enabled
        ports:
          - containerPort: {{ .Values.plausible.service.targetPort }}
            name: http
        volumeMounts:
          - name: plausible-data
            mountPath: /var/lib/plausible
      volumes:
        - name: plausible-data
          persistentVolumeClaim:
            claimName: {{ .Values.plausible.PersistentVolumeClaim.name }}
