apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-config
  namespace: {{ .Values.namespace }}
data:
  CRON_ENABLED: "true"
  MAILER_EMAIL: "no.reply.whgazetteer@gmail.com"
  MAILER_NAME: "WHG Plausible Analytics"
  ADMIN_USER_EMAIL: "whgazetteer@gmail.com"
  ADMIN_USER_NAME: "WHG Admin"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER_NAME: "no.reply.whgazetteer@gmail.com"
  SMTP_HOST_SSL_ENABLED: "true"
  BASE_URL: "https://analytics.whgazetteer.org"
  POSTGRES_HOST: "plausible-postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres" # Security is not a concern here since DB is not exposed
  POSTGRES_INITDB_ARGS: "--nosync --allow-group-access --auth-host=scram-sha-256 --auth-local=trust"
  POSTGRES_INITDB_SKIP_CHOWN: "1"
  PGUSER: "root"
  PGDATA: "/var/lib/postgresql/data"
  DATABASE_URL: "postgresql://postgres:postgres@plausible-postgres:5432/postgres"
  CLICKHOUSE_RUN_AS_ROOT: "1"
  CLICKHOUSE_DO_NOT_CHOWN: "1"
  CLICKHOUSE_SKIP_USER_SETUP: "1"
  DISABLE_REGISTRATION: "true"
