apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-config
  namespace: {{ .Values.namespace }}
data:
  CRON_ENABLED: "true"
  MAILER_EMAIL: "no.reply.whgazetteer@gmail.com"
  MAILER_NAME: "WHG Plausible Analytics"
  ADMIN_USER_EMAIL: "whgazetteer@gmail.com"
  ADMIN_USER_NAME: "WHG Admin"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER_NAME: "no.reply.whgazetteer@gmail.com"
  SMTP_HOST_SSL_ENABLED: "true"
  BASE_URL: "https://analytics.whgazetteer.org"
  POSTGRES_PASSWORD: "postgres" # Security is not a concern here since DB is not exposed
  CLICKHOUSE_RUN_AS_ROOT: "1"
  CLICKHOUSE_DO_NOT_CHOWN: "1"
  CLICKHOUSE_SKIP_USER_SETUP: "1"
  DISABLE_REGISTRATION: "true"
