apiVersion: v2
name: prometheus-grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"

dependencies:
  - name: prometheus
    version: 1.0.0
    repository: file://charts/prometheus
  - name: grafana
    version: 1.0.0
    repository: file://charts/grafana
