apiVersion: batch/v1
kind: Job
metadata:
  name: tippecanoe-job
spec:
  template:
    spec:
      containers:
      - name: tippecanoe
        image: worldhistoricalgazetteer/tippecanoe
        command: ["/bin/bash", "-c"]
        # Use `yq` to replace the following `args` value
        # For example, yq eval '.spec.template.spec.containers[0].args[0] = "/tippecanoe/tippecanoe -o /new/output.mbtiles /new/input.geojson"' -i tippecanoe-job.yaml
        args:
          - /tippecanoe/tippecanoe --help
        volumeMounts:
          - name: tiles
            mountPath: /srv/tiles
      restartPolicy: Never
      volumes:
        - name: tiles
          persistentVolumeClaim:
            claimName: tiles-pvc
  backoffLimit: 4