apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.prometheusPrometheus.pv.storageClassName }}
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner  # using hostPath
reclaimPolicy: Retain  # Ensures data is kept when PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Prevents PV binding until PVC is created
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: {{ .Values.prometheusPrometheus.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.prometheusPrometheus.pv.storageClassName }}
  hostPath:
    path: {{ .Values.prometheusPrometheus.pv.path }}
  nodeAffinity:
    required: {{ toYaml .Values.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheusPrometheus.pv.storage }}
  storageClassName: {{ .Values.prometheusPrometheus.pv.storageClassName }}