namespace: "whg"

wordpress:
  image: wordpress:6.5-apache
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    type: NodePort
    port: 80
    targetPort: 8082
    nodePort: 30083
  persistentVolume:
    name: pv-wordpress
    persistentVolumeReclaimPolicy: Retain
    volumeSize: 1Gi
    hostPath: /home/gazetteer/localdata/pv/wordpress
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
  PersistentVolumeClaim:
    name: pvc-wordpress

mariadb:
  image: mariadb:11.3
  imagePullPolicy: IfNotPresent
  replicas: 1
  persistentVolume:
    name: pv-mariadb
    persistentVolumeReclaimPolicy: Retain
    volumeSize: 1Gi
    hostPath: /home/gazetteer/localdata/pv/mariadb
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
  PersistentVolumeClaim:
    name: pvc-mariadb

env:
  - name: DB_HOST
    valueFrom:
        secretKeyRef:
          name: whg-secret
          key: wordpress-db-host
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: whg-secret
        key: wordpress-db-user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: whg-secret
        key: wordpress-db-password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: whg-secret
        key: wordpress-db-name
