wordpress:
  image: wordpress:6.5-apache
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80
  volumeSize: 1Gi

mariadb:
  image: mariadb:11.3
  imagePullPolicy: IfNotPresent
  volumeSize: 1Gi

secretName: whg-secret
