apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tileserver-gl-ingress
  annotations:
    networking.k8s.io/ingress.class: contour
    ingress.kubernetes.io/force-ssl-redirect: "true" # Redirect HTTP to HTTPS
    cert-manager.io/cluster-issuer: letsencrypt-prod  # For automated TLS certificates using Cert-Manager
spec:
  tls:
  - hosts:
    - tileserver.whgazetteer.org
    secretName: tileserver-tls-secret
  rules:
    - host: tileserver.whgazetteer.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tileserver-gl
                port:
                  number: 80
