apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver-gl
  labels:
    app: tileserver-gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tileserver-gl
  template:
    metadata:
      labels:
        app: tileserver-gl
    spec:
      containers:
      - name: tileserver-gl
        image: maptiler/tileserver-gl:v5.0.0
#        image: maptiler/tileserver-gl-light:v5.0.0
        command:
          - "node"
          - "/usr/src/app/src/main.js"
          - "--config"
          - "/usr/src/app/tiles/configs/config.json"
        workingDir: /usr/src/app
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: tiles
            mountPath: /usr/src/app/tiles
          - name: assets
            mountPath: /usr/src/app/assets
            readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: tiles
          persistentVolumeClaim:
            claimName: tiles-pvc
        # Add the following dynamically to correctly identify the path to the assets directory
        # - name: assets
        #   hostPath:
        #     path: /path/to/assets
        #     type: Directory