apiVersion: v1
kind: PersistentVolume
metadata:
  name: tiles-pv
spec:
  capacity:
    storage: 50Gi  # Adjust size as needed based on anticipated tile data
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/k8s/tiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - all
          - general
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust size as needed based on anticipated tile data
  storageClassName: ""