subdomain: "map.whgazetteer.org"
namespace: "whg"

securityContext:
  runAsUser: 999
  runAsGroup: 999

service:
  type: "LoadBalancer" # May be overridden by Helm argument
  tileapi:
    port: 8081
    targetPort: 8081
    servicePort: 30081
  tileserver:
    port: 8080
    targetPort: 8080
    servicePort: 30080

replicaCount: 1

tileapi:
  image: "worldhistoricalgazetteer/tileapi"
  imageTag: "0.0.8"
  imagePullPolicy: "IfNotPresent"
#  port: 8081
#  servicePort: 81
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

tileserver:
  image: "maptiler/tileserver-gl"
  imageTag: "v5.0.0"
  imagePullPolicy: "IfNotPresent"
  git:
    url: "https://github.com/WorldHistoricalGazetteer/place.git"
    sourceFolder: "tileserver/repository"
    targetFolder: "src"
  resources:
    requests:
      memory: "2Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "4"

tippecanoe:
  image: "worldhistoricalgazetteer/tippecanoe"
  imageTag: "v0.0.2"
  imagePullPolicy: "IfNotPresent"

vespa:
  namespace: "whg"

pv:
  tiles:
    storage: 50Gi
    path: /data/k8s/tiles
    mountPath: /mnt/data/tiles
  repository:
    name: tileserver-repository
    mountPath: /mnt/tileserver-repository
    gitFolder: /tileserver/repository   # 👈 relative subfolder within repo

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tileserver
              operator: In
              values:
                - "true"