subdomain: "map.whgazetteer.org"
namespace: "tileserver"

securityContext:
  runAsUser: 999
  runAsGroup: 999

service:
  type: "LoadBalancer" # May be overridden by Helm argument
  tileapi:
    port: 8081
    targetPort: 8081
    servicePort: 30081
  tileserver:
    port: 8080
    targetPort: 8080
    servicePort: 30080

replicaCount: 1

tileapi:
  image: "worldhistoricalgazetteer/tileapi"
  imageTag: "0.0.5"
  imagePullPolicy: "IfNotPresent"
#  port: 8081
#  servicePort: 81
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

tileserver:
  image: "maptiler/tileserver-gl"
  imageTag: "v5.0.0"
  imagePullPolicy: "IfNotPresent"
  git:
    url: "https://github.com/WorldHistoricalGazetteer/place.git"
    sourceFolder: "tileserver/repository"
    targetFolder: "src"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

tippecanoe:
  image: "worldhistoricalgazetteer/tippecanoe"
  imageTag: "v0.0.2"
  imagePullPolicy: "IfNotPresent"

pv:
  tiles:
    storage: 50Gi
    path: /data/k8s/tiles
    mountPath: /mnt/data/tiles
  tileserver:
    storage: 10Gi
    path: /data/k8s/tileserver
    api:
      mountPath: /opt/api
      subPath: src/tileserver/repository/api
    configs:
      mountPath: /mnt/data/configs
      subPath: configs
    reconfiguration:
      mountPath: /opt/reconfiguration
      subPath: src/tileserver/repository/reconfiguration
    assets:
      mountPath: /mnt/data/assets
      subPath: src/tileserver/repository/assets
    mapdata:
      mountPath: /mnt/data/mapdata
      subPath: mapdata

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tileserver
              operator: In
              values:
                - "true"