apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: django
    component: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
      component: celery-worker
  template:
    metadata:
      labels:
        app: django
        component: celery-worker
    spec:
      initContainers:
        - name: create-user
          image: busybox:1.35.0-uclibc
          command:
            - "/bin/sh"
            - "-c"
            - |
              adduser -D whgadmin
              echo "whgadmin:$user-password" | chpasswd
          envFrom:
            - secretRef:
                name: whg-secret
      containers:
        - name: celery-worker
          image: worldhistoricalgazetteer/web:${IMAGE_VERSION}"
          command: ["celery", "-A", "whg", "worker", "--loglevel=debug"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "whg.settings"
            - name: IMAGE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: whg-config
                  key: image-version
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep 'celery worker' | grep -v grep
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe: # Wait until redis is available
            exec:
              command:
                - "sh"
                - "-c"
                - "nc -z redis 6379"
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: shared-volume
          emptyDir: {}
