apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: django
    component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      component: celery-beat
  template:
    metadata:
      labels:
        app: django
        component: celery-beat
    spec:
      initContainers:
        - name: create-user
          image: busybox:1.35.0-uclibc
          command:
            - "/bin/sh"
            - "-c"
            - |
              adduser -D whgadmin
              echo "whgadmin:$user-password" | chpasswd
          envFrom:
            - secretRef:
                name: whg-secret
      containers:
        - name: celery-beat
          image: worldhistoricalgazetteer/web:latest
          command: ["/bin/bash", "-c", "rm -f /app/celerybeat.pid && celery -A whg beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "whg.settings"
            - name: IMAGE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: whg-config
                  key: image-version
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
          readinessProbe: # Wait until redis is available
            exec:
              command:
                - "sh"
                - "-c"
                - "nc -z redis 6379"
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: shared-volume
          emptyDir: {}
