apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/k8s/django-app  # Path on the host system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: django-app-pv  # Reference the PV
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-static-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/k8s/django-static  # Path on the host system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: django-static-pv  # Reference the PV
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-media-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/k8s/django-media  # Path on the host system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-media-pv  # Reference the PV
  storageClassName: ""
