apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: git-sync
          image: alpine/git
          command: ["git", "clone", "-b", "main", "https://github.com/WorldHistoricalGazetteer/whg3.git", "/app"]
          volumeMounts:
            - name: app
              mountPath: /app
        - name: create-user
          image: busybox:1.35.0-uclibc
          command:
            - "/bin/sh"
            - "-c"
            - |
              adduser -D whgadmin
              echo "whgadmin:$user-password" | chpasswd
          envFrom:
            - secretRef:
                name: whg-secret
        - name: collectstatic
          image: python:3.9
          command: ["sh", "-c", "python manage.py collectstatic --no-input"]
          volumeMounts:
            - name: static-files
              mountPath: /app/static
      containers:
        - name: django-container
          image: worldhistoricalgazetteer/web:${IMAGE_VERSION}"
          command: ["gunicorn", "whg.wsgi:application", "--bind", "0.0.0.0:443", "--timeout", "1200", "-w", "4"]
          ports:
            - containerPort: 443
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "whg.settings"
            - name: IMAGE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: whg-config
                  key: image-version
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: whg-config
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: whg-secret
                  key: db-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: whg-config
                  key: db-name
            - name: DATABASE_URL
              value: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: whg-secret
                  key: secret-key
          volumeMounts:
            - name: app
              mountPath: /app
            - name: static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
            - name: config-volume
              mountPath: /app/config/configMap
              readOnly: true
            - name: secret-volume
              mountPath: /app/config/secret
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe: # Wait until the database is ready
            exec:
              command:
                - "sh"
                - "-c"
                - "nc -z postgres 5432"
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: app
          emptyDir: {}
        - name: static-files
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: media-files
          persistentVolumeClaim:
            claimName: django-media-pvc
        - name: config-volume
          configMap:
            name: whg-config
        - name: secret-volume
          secret:
            secretName: whg-secret
