apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgbackrest-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: django-pgbackrest
  local:
    path: /data/k8s/pgbackrest
