apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpack
  labels:
    app: webpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpack
  template:
    metadata:
      labels:
        app: webpack
    spec:
      initContainers:
        - name: webpack-build
          image: node:18-alpine
          command:
            - "/bin/bash"
            - "-c"
            - |
              cd /app
              npm install
              npx webpack --config webpack.config.js
          volumeMounts:
            - name: app-volume
              mountPath: /app
      containers:
      - name: webpack
        image: node:18-alpine
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: /usr/src/app
          name: webpack-source
        workingDir: /usr/src/app
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: webpack-source
        configMap:
          name: webpack-config
