apiVersion: v1
kind: PersistentVolume
metadata:
  name: webpack-build-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "webpack-build-storage"
  hostPath:
    path: /data/k8s/webpack
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: environment
          operator: In
          values:
          - development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpack-build-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "webpack-build-storage"
