import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)


class TypesProcessor:
    def __init__(self, place_type: str, admin_level: str):
        """
        :param place_type: OSM-derived place type.
        """
        self.place_type = place_type
        self.admin_level = admin_level

        self.dictionary = {
            "abbey": {'AAT': '300000642', 'GeoNames': None},
            "abbey-church": {'AAT': '300007495', 'GeoNames': None},
            "acropolis": {'AAT': '300000700', 'GeoNames': None},
            "agora": {'AAT': '300008074', 'GeoNames': None},
            "plaza": {'AAT': None, 'GeoNames': None},
            "amphitheatre": {'AAT': '300007128', 'GeoNames': None},
            "anchorage": {'AAT': '300386968', 'GeoNames': None},
            "aqueduct": {'AAT': None, 'GeoNames': None},
            "arch": {'AAT': '300000994', 'GeoNames': None},
            "archaeological-site": {'AAT': '300000810', 'GeoNames': None},
            "archipelago": {'AAT': None, 'GeoNames': None},
            "architecturalcomplex": {'AAT': None, 'GeoNames': None},
            "archive-repository": {'AAT': '300264596', 'GeoNames': None},
            "barracks": {'AAT': '300005665', 'GeoNames': None},
            "basilica": {'AAT': None, 'GeoNames': None},
            "bath": {'AAT': None, 'GeoNames': None},
            "bay": {'AAT': None, 'GeoNames': None},
            "bridge": {'AAT': '300007836', 'GeoNames': None},
            "building": {'AAT': None, 'GeoNames': None},
            "cairn": {'AAT': '300006960', 'GeoNames': None},
            "canal": {'AAT': '300006075', 'GeoNames': None},
            "canyon": {'AAT': '300008763', 'GeoNames': None},
            "cape": {'AAT': None, 'GeoNames': None},
            "cascade": {'AAT': '300006792', 'GeoNames': None},
            "castellum": {'AAT': '300008450', 'GeoNames': None},
            "castle": {'AAT': '300006891', 'GeoNames': None},
            "cemetery": {'AAT': None, 'GeoNames': None},
            "rapid": {'AAT': None, 'GeoNames': None},
            "causeway": {'AAT': None, 'GeoNames': None},
            "cave": {'AAT': None, 'GeoNames': None},
            "centuriation": {'AAT': None, 'GeoNames': None},
            "ceramicproduction": {'AAT': None, 'GeoNames': None},
            "channel-artificial": {'AAT': '300133792', 'GeoNames': None},
            "church-2": {'AAT': '300007466', 'GeoNames': None},
            "fortified-church": {'AAT': '300263447', 'GeoNames': None},
            "church": {'AAT': None, 'GeoNames': None},
            "circus": {'AAT': None, 'GeoNames': None},
            "cistern": {'AAT': '300052558', 'GeoNames': None},
            "citadel": {'AAT': '300006902', 'GeoNames': None},
            "city-block": {'AAT': '300008077', 'GeoNames': None},
            "city-center": {'AAT': None, 'GeoNames': None},
            "coast": {'AAT': None, 'GeoNames': None},
            "coastal-change": {'AAT': None, 'GeoNames': None},
            "cultural-landscape": {'AAT': '300008932', 'GeoNames': None},
            "dam": {'AAT': None, 'GeoNames': None},
            "delta": {'AAT': '300008760', 'GeoNames': None},
            "deme-attic": {'AAT': None, 'GeoNames': None},
            "desert": {'AAT': None, 'GeoNames': None},
            "diocese-church": {'AAT': '300000799', 'GeoNames': None},
            "diocese-roman": {'AAT': None, 'GeoNames': None},
            "district": {'AAT': '300000705', 'GeoNames': None},
            "earthwork": {'AAT': None, 'GeoNames': None},
            "ekklesiasterion": {'AAT': None, 'GeoNames': None},
            "escarpment": {'AAT': '300132353', 'GeoNames': None},
            "estate": {'AAT': None, 'GeoNames': None},
            "estuary": {'AAT': '300266571', 'GeoNames': None},
            "false": {'AAT': None, 'GeoNames': None},
            "farm": {'AAT': None, 'GeoNames': None},
            "fiction": {'AAT': None, 'GeoNames': None},
            "findspot": {'AAT': None, 'GeoNames': None},
            "fishpond": {'AAT': None, 'GeoNames': None},
            "forest": {'AAT': None, 'GeoNames': None},
            "fort-2": {'AAT': '300006909', 'GeoNames': None},
            "fort-group": {'AAT': None, 'GeoNames': None},
            "fort": {'AAT': None, 'GeoNames': None},
            "fortlet": {'AAT': '300006910', 'GeoNames': None},
            "forum": {'AAT': '300008085', 'GeoNames': None},
            "fountain": {'AAT': None, 'GeoNames': None},
            "frontier-system-limes": {'AAT': None, 'GeoNames': None},
            "garden-hortus": {'AAT': None, 'GeoNames': None},
            "city-gate": {'AAT': None, 'GeoNames': None},
            "gateway": {'AAT': '300069189', 'GeoNames': None},
            "gorge": {'AAT': '300008767', 'GeoNames': None},
            "grama": {'AAT': None, 'GeoNames': None},
            "grove": {'AAT': None, 'GeoNames': None},
            "gymnasium": {'AAT': '300007297', 'GeoNames': None},
            "harbor": {'AAT': None, 'GeoNames': None},
            "hill": {'AAT': None, 'GeoNames': None},
            "hillfort": {'AAT': '300006911', 'GeoNames': None},
            "hunting-base": {'AAT': '300387322', 'GeoNames': None},
            "island": {'AAT': None, 'GeoNames': None},
            "isthmus": {'AAT': None, 'GeoNames': None},
            "lagoon": {'AAT': None, 'GeoNames': None},
            "lake": {'AAT': None, 'GeoNames': None},
            "league": {'AAT': '300387505', 'GeoNames': None},
            "lighthouse": {'AAT': '300007741', 'GeoNames': None},
            "label": {'AAT': None, 'GeoNames': None},
            "marsh-wetland": {'AAT': None, 'GeoNames': None},
            "metalworking": {'AAT': '300169784', 'GeoNames': None},
            "milestone": {'AAT': '300006973', 'GeoNames': None},
            "military-base": {'AAT': '300000455', 'GeoNames': None},
            "military-installation-or-camp-temporary": {'AAT': None, 'GeoNames': None},
            "mine-2": {'AAT': '300000390', 'GeoNames': None},
            "mine": {'AAT': None, 'GeoNames': None},
            "monastery": {'AAT': '300000641', 'GeoNames': None},
            "monument": {'AAT': '300006958', 'GeoNames': None},
            "mosque": {'AAT': None, 'GeoNames': None},
            "mountain": {'AAT': '300008795', 'GeoNames': None},
            "nome-gr": {'AAT': None, 'GeoNames': None},
            "nome-egyptian": {'AAT': None, 'GeoNames': None},
            "nuraghe": {'AAT': '300005727', 'GeoNames': None},
            "oasis": {'AAT': None, 'GeoNames': None},
            "odeon": {'AAT': '300127075', 'GeoNames': None},
            "pagus": {'AAT': None, 'GeoNames': None},
            "palace": {'AAT': '300005734', 'GeoNames': None},
            "palace-complex": {'AAT': '300417317', 'GeoNames': None},
            "palaistra": {'AAT': None, 'GeoNames': None},
            "pass": {'AAT': '300259572', 'GeoNames': None},
            "peninsula": {'AAT': None, 'GeoNames': None},
            "people": {'AAT': '300387177', 'GeoNames': None},
            "piscina-roman": {'AAT': '300375619', 'GeoNames': None},
            "plain": {'AAT': None, 'GeoNames': None},
            "plateau": {'AAT': None, 'GeoNames': None},
            "platform": {'AAT': '300375665', 'GeoNames': None},
            "polis": {'AAT': '300008397', 'GeoNames': None},
            "port": {'AAT': None, 'GeoNames': None},
            "postern": {'AAT': '300002932', 'GeoNames': None},
            "priory": {'AAT': '300000645', 'GeoNames': None},
            "production": {'AAT': None, 'GeoNames': None},
            "province-2": {'AAT': '300000774', 'GeoNames': None},
            "province": {'AAT': None, 'GeoNames': None},
            "pyramid": {'AAT': '300004838', 'GeoNames': None},
            "quarry": {'AAT': '300000402', 'GeoNames': None},
            "regio-augusti": {'AAT': None, 'GeoNames': None},
            "region": {'AAT': None, 'GeoNames': None},
            "reservoir": {'AAT': None, 'GeoNames': None},
            "ridge": {'AAT': '300266640', 'GeoNames': None},
            "mouth": {'AAT': '300387057', 'GeoNames': None},
            "river": {'AAT': None, 'GeoNames': None},
            "road": {'AAT': None, 'GeoNames': None},
            "room": {'AAT': '300004044', 'GeoNames': None},
            "ruin": {'AAT': '300008057', 'GeoNames': None},
            "salt-pan-salina": {'AAT': None, 'GeoNames': None},
            "salt-marsh": {'AAT': None, 'GeoNames': None},
            "sanctuary": {'AAT': '300391482', 'GeoNames': None},
            "satrapy": {'AAT': '300235102', 'GeoNames': None},
            "settlement": {'AAT': '300008347', 'GeoNames': None},
            "fortified-settlement": {'AAT': '300387238', 'GeoNames': None},
            "settlement-modern": {'AAT': None, 'GeoNames': None},
            "sewer": {'AAT': None, 'GeoNames': None},
            "shrine": {'AAT': '300007558', 'GeoNames': None},
            "siege-mine": {'AAT': None, 'GeoNames': None},
            "siege-ramp": {'AAT': None, 'GeoNames': None},
            "slag-heap": {'AAT': None, 'GeoNames': None},
            "space-exterior-covered": {'AAT': '300075459', 'GeoNames': None},
            "space-interior": {'AAT': '300078790', 'GeoNames': None},
            "space-uncovered": {'AAT': '300075460', 'GeoNames': None},
            "spring": {'AAT': '300008697', 'GeoNames': None},
            "stadion": {'AAT': None, 'GeoNames': None},
            "state": {'AAT': '300232420', 'GeoNames': None},
            "station": {'AAT': None, 'GeoNames': None},
            "stoa": {'AAT': None, 'GeoNames': None},
            "strait": {'AAT': None, 'GeoNames': None},
            "street": {'AAT': '300008247', 'GeoNames': None},
            "stupa": {'AAT': None, 'GeoNames': None},
            "synagogue": {'AAT': '300007590', 'GeoNames': None},
            "taberna-shop": {'AAT': None, 'GeoNames': None},
            "tell": {'AAT': '300008545', 'GeoNames': None},
            "temple-2": {'AAT': '300007595', 'GeoNames': None},
            "temple": {'AAT': None, 'GeoNames': None},
            "theatre": {'AAT': None, 'GeoNames': None},
            "tomb": {'AAT': '300005926', 'GeoNames': None},
            "tower-division": {'AAT': '300003615', 'GeoNames': None},
            "tower-church": {'AAT': '300003625', 'GeoNames': None},
            "tower-defensive": {'AAT': '300004862', 'GeoNames': None},
            "tower-gate": {'AAT': '300003627', 'GeoNames': None},
            "tower-single": {'AAT': '300004847', 'GeoNames': None},
            "tower-wall": {'AAT': '300003639', 'GeoNames': None},
            "tower-mill": {'AAT': '300411567', 'GeoNames': None},
            "tower-tomb": {'AAT': '300120649', 'GeoNames': None},
            "townhouse": {'AAT': None, 'GeoNames': None},
            "treasury": {'AAT': '300006050', 'GeoNames': None},
            "tribus": {'AAT': None, 'GeoNames': None},
            "tumulus": {'AAT': None, 'GeoNames': None},
            "tunnel": {'AAT': None, 'GeoNames': None},
            "undefined": {'AAT': None, 'GeoNames': None},
            "underground-structures": {'AAT': '300008047', 'GeoNames': None},
            "unknown": {'AAT': None, 'GeoNames': None},
            "unlocated": {'AAT': None, 'GeoNames': None},
            "urban": {'AAT': None, 'GeoNames': None},
            "valley": {'AAT': None, 'GeoNames': None},
            "vicus": {'AAT': None, 'GeoNames': None},
            "villa": {'AAT': '300005517', 'GeoNames': None},
            "volcano": {'AAT': '300132325', 'GeoNames': None},
            "wall-2": {'AAT': '300002469', 'GeoNames': None},
            "defensive-wall": {'AAT': '300002485', 'GeoNames': None},
            "interior-wall": {'AAT': '300002535', 'GeoNames': None},
            "city-wall": {'AAT': '300005072', 'GeoNames': None},
            "wall": {'AAT': None, 'GeoNames': None},
            "water-inland": {'AAT': None, 'GeoNames': None},
            "water-feature": {'AAT': '300180674', 'GeoNames': None},
            "wheel": {'AAT': None, 'GeoNames': None},
            "water-open": {'AAT': None, 'GeoNames': None},
            "watercourse": {'AAT': '300387091', 'GeoNames': None},
            "waterfall": {'AAT': '300008736', 'GeoNames': None},
            "well": {'AAT': None, 'GeoNames': None},
            "whirlpool": {'AAT': None, 'GeoNames': None},
            "ziggurat": {'AAT': '300007626', 'GeoNames': None},
        }

    def process(self) -> Dict[str, Any]:

        # TODO: REMOVE THIS BLOCK
        return {
            "types": [self.place_type, self.admin_level],
        }

        types = []
        classes = []
        entry = self.dictionary.get(self.place_type)
        if entry:
            for key, target_list in [('AAT', types), ('GeoNames', classes)]:
                value = entry.get(key)
                if value:
                    target_list.append(value)

        # logger.info(f"Found AAT types: {types}")
        # logger.info(f"Found GeoNames classes: {classes}")

        return {
            **({"types": types} if types else {}),
            **({"classes": classes} if classes else {}),
        }
