import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)


class TypesProcessor:
    def __init__(self, place_type: str):
        """
        :param place_type: OSM-derived place type.
        """
        self.place_type = place_type

        self.dictionary = {
            # Types are prefiltered by ['geological', 'historic', 'place', 'water', 'waterway']

            # Geological https://wiki.openstreetmap.org/wiki/Map_features#Geological
            "moraine": "T",
            "outcrop": "T",
            "volcanic_caldera_rim": "T",
            "fault": "T",
            "fold": "T",
            "palaeontological_site": "S",
            "volcanic_lava_field": "T",
            "volcanic_vent": "T",
            "glacial_erratic": "T",
            "rock_glacier": "T",
            "giants_kettle": "T",
            "meteor_crater": "T",
            "hoodoo": "T",
            "columnar_jointing": "T",
            "dyke": "T",
            "monocline": "T",
            "tor": "T",
            "unconformity": "T",
            "cone": "T",
            "sinkhole": "T",
            "pingo": "T",
            "inselberg": "T",
            "limestone_pavement": "T",
            # Historic https://wiki.openstreetmap.org/wiki/Map_features#Historic
            "aircraft": "S",
            "anchor": "S",
            "aqueduct": "S",
            "archaeological_site": "S",
            "battlefield": "S",
            "bomb_crater": "T",
            "boundary_stone": "S",
            "building": "S",
            "bullaun_stone": "S",
            "cannon": "S",
            "castle": "S",
            "castle_wall": "S",
            "cattle_crush": "S",
            "charcoal_pile": "S",
            "church": "S",
            "city_gate": "S",
            "citywalls": "S",
            "creamery": "S",
            "epigraph": "S",
            "fort": "S",
            "gallows": "S",
            "house": "S",
            "high_cross": "S",
            "highwater_mark": "S",
            "lavoir": "S",
            "lime_kiln": "S",
            "locomotive": "S",
            "machine": "S",
            "manor": "S",
            "memorial": "S",
            "milestone": "S",
            "millstone": "S",
            "mine": "S",
            "minecart": "S",
            "monastery": "S",
            "monument": "S",
            "mosque": "S",
            "ogham_stone": "S",
            "optical_telegraph": "S",
            "pa": "S",
            "pillory": "S",
            "pound": "S",
            "railway_car": "S",
            "road": "S",
            "round_tower": "S",
            "ruins": "S",
            "rune_stone": "S",
            "shieling": "S",
            "ship": "S",
            "stećak": "S",
            "stone": "S",
            "tank": "S",
            "temple": "S",
            "tomb": "S",
            "tower": "S",
            "vehicle": "S",
            "wayside_cross": "S",
            "wayside_shrine": "S",
            "wreck": "S",
            "yes": "S",
            # Place https://wiki.openstreetmap.org/wiki/Map_features#Place
            "country": "A",
            "state": "A",
            "region": "A",
            "province": "A",
            "district": "A",
            "county": "A",
            "subdistrict": "A",
            "municipality": "A",
            "city": "P",
            "borough": "P",
            "suburb": "P",
            "quarter": "P",
            "neighbourhood": "P",
            "city_block": "P",
            "plot": "P",
            "town": "P",
            "village": "P",
            "hamlet": "P",
            "isolated_dwelling": "P",
            "farm": "S",
            "allotments": "S",
            "continent": "L",
            "archipelago": "L",
            "island": "L",
            "islet": "L",
            "square": "L",
            "locality": "L",
            "polder": "L",
            "sea": "H",
            "ocean": "H",
            # Water https://wiki.openstreetmap.org/wiki/Map_features#Water
            "river": "H",
            "oxbow": "H",
            "canal": "H",
            "ditch": "H",
            "lock": "H",
            "fish_pass": "H",
            "lake": "H",
            "reservoir": "H",
            "pond": "H",
            "basin": "H",
            "lagoon": "H",
            "stream_pool": "H",
            "reflecting_pool": "H",
            "moat": "H",
            "wastewater": "H",
            # Waterway https://wiki.openstreetmap.org/wiki/Map_features#Waterway
            "riverbank": "H",
            "stream": "H",
            "tidal_channel": "H",
            "drain": "H",
            "pressurised": "H",
            "fairway": "H",
            "dock": "H",
            "boatyard": "H",
            "dam": "H",
            "weir": "H",
            "waterfall": "H",
            "lock_gate": "H",
            "soakhole": "H",
            "turning_point": "H",
            "water_point": "H",
            "fuel": "H",
        }

    def process(self) -> Dict[str, Any]:

        return {
            **({"classes": [entry]} if (entry := self.dictionary.get(self.place_type)) else {}),
        }
