apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        imagePullPolicy: {{ .Values.wordpress.imagePullPolicy }}
        ports:
          - containerPort: 80
        envFrom:
          - secretRef:
              name: {{ .Values.secretName }}
        volumeMounts:
          - name: wp-content
            mountPath: /var/www/html/wp-content
            subPath: wordpress/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: ishi-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image }}
        imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
        envFrom:
          - secretRef:
              name: {{ .Values.secretName }}
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
            subPath: wordpress/mariadb
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: ishi-pvc
