apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env: {{ toYaml .Values.env | nindent 10 }}
        imagePullPolicy: {{ .Values.wordpress.imagePullPolicy }}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wp-content
            mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: {{ .Values.wordpress.PersistentVolumeClaim.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image }}
        env: {{ toYaml .Values.env | nindent 10 }}
        imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.PersistentVolumeClaim.name }}
