apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-host
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-name
        imagePullPolicy: {{ .Values.wordpress.imagePullPolicy }}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wp-content
            mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: {{ .Values.wordpress.PersistentVolumeClaim.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mariadb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image }}
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-name
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: whg-secret
                key: wordpress-db-password
        imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.PersistentVolumeClaim.name }}
