apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      {{- if eq .Values.wordpress.service.type "NodePort" }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
      {{- end }}
  selector:
    app: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mariadb.service.type }}
  selector:
    app: mariadb
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.targetPort }}
