apiVersion: v1
kind: PersistentVolume
metadata:
  name: glitchtip-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glitchtip-storage
  hostPath:
    path: /data/k8s/glitchtip
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - all
          - general
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: glitchtip-storage