image:
  repository: glitchtip/glitchtip
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  storage: 5Gi

redis:
  image: redis:7

secrets:
  name: whg-secret
  #  TODO: Add the following secrets to the https://github.com/WorldHistoricalGazetteer/secrets repository so that
  #  they can be automatically injected into the whg-secret Kubernetes secret.
  #  POSTGRES_USER: <your-postgres-username>
  #  POSTGRES_PASSWORD: <your-postgres-password>
  #  GLITCHTIP_SECRET_KEY: <django-secret-key>
  #  DATABASE_URL: postgres://<user>:<password>@postgres:5432/glitchtip
  #  REDIS_URL: redis://redis:6379

service:
  type: ClusterIP
  port: 80
