apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-vespa-app
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
spec:
  ttlSecondsAfterFinished: 300 # Automatically clean up job after 5 minutes
  template:
    spec:
      initContainers: # Init container to force wait for readiness of configservers
        - {{- tpl .Values.common.initContainer $ | nindent 10 }}
      containers:
      - name: deploy-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo "Deploying Vespa application package...";
            ls -l /vespa/application
            cat /vespa/application/hosts.xml
            cat /vespa/application/services.xml
            vespa-deploy prepare /vespa/application && vespa-deploy activate
            echo "Deployment complete.";
        envFrom:
          - configMapRef:
              name: vespa-config
        volumeMounts:
          - name: vespa-application-config-files
            mountPath: /vespa/application-config
            readOnly: true
      volumes:
        - name: vespa-application-config-files
          configMap:
            name: vespa-application-config-files
      restartPolicy: Never
