apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa-feed-container
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCounts.feed }}
  selector:
    matchLabels:
      app: vespa-feed-container
      name: vespa-internal
  serviceName: vespa-internal
  template:
    metadata:
      labels:
        app: vespa-feed-container
        name: vespa-internal
    spec:
      initContainers: # Init container to force wait for readiness of configservers
        - {{- tpl .Values.common.initContainer $ | nindent 10 }}
      containers:
      - name: vespa-feed-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: ["services"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext: {{- toYaml .Values.securityContext.container | nindent 10 }}
        envFrom:
        - configMapRef:
            name: vespa-config
        resources: {{- toYaml .Values.resources.feed | nindent 10 }}