apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vespa-ingestion-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner  # using hostPath
reclaimPolicy: Retain  # Ensures data is kept when PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Prevents PV binding until PVC is created
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vespa-ingestion-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.ingestion.pv.storageSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vespa-ingestion-storage
  local:
    path: "{{ .Values.ingestion.pv.rootPath }}"
  nodeAffinity: {{ toYaml .Values.nodeAffinities.content | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vespa-ingestion-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ingestion.pv.storageSize }}
  storageClassName: vespa-ingestion-storage
  volumeMode: Filesystem
  volumeName: vespa-ingestion-pv