{{- range .Values.pv }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-pv
spec:
  capacity:
    storage: {{ .storageSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .name }}-storage
  hostPath:
    path: "/data/k8s/vespa-{{ .name }}"
  nodeAffinity: {{ toYaml $.Values.nodeAffinities.admin | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storageSize }}
  storageClassName: {{ .name }}-storage
---
{{- end }}