apiVersion: v1
kind: Service
metadata:
  name: vespa-feed
  namespace: {{ .Values.namespace }}
  labels:
    app: vespa
spec:
  selector:
    app: vespa
    role: feed
  ports:
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080