name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the build on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs-source/requirements.txt

      # Build the documentation
      - name: Build documentation
        run: |
          cd docs-source  # Change to the /docs-source directory
          make clean
          make html

      # Copy the built files to the /docs folder for GitHub Pages
      - name: Copy built files for GitHub Pages
        run: |
          mkdir -p docs  # Ensure the docs folder exists for GitHub Pages
          cp -r docs-source/_build/html/* docs/

      # Commit the built files to the main branch
      - name: Commit and push documentation to main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f docs/*  # Add the built HTML files in the docs folder
          git commit -m "Deploy documentation"
          git push origin main  # Push the built files to the main branch
