apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}-web
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web